name: Build & Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Census API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_UNAME }}
          key: ${{ secrets.SSH_KEY }}

     
          script:
            git clone https://github.com/geospackle/better-census-api.git
            docker-compose -f go-app-compose.yaml up -d --build
            echo 'Deployment successful to digital ocean'
