name: Rebuild
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Deploy Census API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_UNAME }}
          key: ${{ secrets.SSH_KEY }}

     
          script:
            docker stop census-api
            docker rm census-api
            docker build . -t census-api
            docker run --detach  -p 127.0.0.1:5000:5000/tcp --env "VIRTUAL_HOST=better-census-api.com" --env "LETSENCRYPT_HOST=better-census-api.com" --env "HTTPS_METHOD=noredirect" census-api
            echo 'Docker was updated'
