name: Build & Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Go API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_UNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir census-api-test
            cd census-api-test
            git clone git@github.com:geospackle/better-census-api.git
            docker-compose -f go-app-compose.yaml up -d --build
            echo 'Deployment successful to digital ocean'
